version: '3'

services:
  jenkins:
    privileged: true
    build: ./jenkins
    restart: always
    ports:
        - "9080:8080"
        - "50010:50000"
    expose:
        - "8080"
        - "50000"
    volumes:
        - './jenkins_home:/var/jenkins_home'
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        TZ: "Asia/Seoul"